name: Run

on:
  schedule:
    # 7:30a every day (UTC-6)
    - cron: '30 13 * * *'

jobs:

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run
      run: go run .

